### PR TITLE
Russian Translation

### PR DESCRIPTION
**Pull request by Rongarah**

### CODE REVIEW

**Comment by Rongarah** [comment]
Sorry if I've done something wrong. Never, uh, used GitHub before :)

**Comment by Floogen** [comment]
It is no problem! I'll be updating your PR shortly to include some lines I had forgotten to add to `default.json` and move your changes into `ru.json`.

Thank you for your help in translating Stardrop, I greatly appreciate it!

**Comment by Rongarah** [comment]
Great, just fixed some spelling errors in that commit.

**Comment by Floogen** [comment]
I've moved over your latest changes into `ru.json`. If you have a moment, could you review it to [confirm it looks alright](https://github.com/Floogen/Stardrop/blob/b8625aeb4aab4fbbccd3168d3c50b3f67dffd489/Stardrop/i18n/ru.json)?

Thank you again for translating Stardrop!

**Comment by Rongarah** [comment]
Alright, here's translated new lines under // Warnings:
```
  "ui.warning.unable_to_locate_smapi": "Не удалось найти StardewModdingAPI.exe\n\nУкажите правильный путь к файлу в разделе\nПросмотр > Настройки",
  "ui.warning.mod_config_saved_but_not_enabled": "Настройки конфигурации модификации сохранены в профиле {0}, однако конфигурации модификаций для конкретных профилей не включены\.\n\nПерейдите в раздел Просмотр> Настройки и установите флажок перед \"Включить Конфигурации Модификаций для Конкретных Профилей\" чтобы Stardrop автоматически сохраняла и применяла изменения конфигурации модификаций.",
  "ui.warning.unable_to_determine_profile": "Невозможно определить выбранный профиль.\n\nSMAPI не будет запущен.",
  "ui.warning.stardrop_up_to_date": "Версия Stardrop актуальна.\n\n{0} - это последняя версия.",
  "ui.warning.update_cooldown_minutes": "Обновления можно запрашивать только раз в 5 минут.\n\nПожалуйста, повторите попытку через {0} мин.",
  "ui.warning.update_cooldown_seconds": "Обновления можно запрашивать только раз в 5 минут.\n\nПожалуйста, повторите попытку через {0} сек.",
  "ui.warning.unable_to_locate_log": "Не удалось найти SMAPI-latest.txt! SMAPI должен успешно запуститься хотя бы один раз, чтобы Stardrop могла обнаружить детали игры.",
  "ui.warning.unable_to_read_log": "Не удалось прочитать журнальный файл SMAPI, чтобы получить версию игры.\n\nМодификации не будут проверяться на наличие обновлений.",
  "ui.warning.no_manifest": "manifest.json не найден в \"{0}\"",
  "ui.warning.unable_to_load_mod": "Не удалось загрузить файл, расположенный в папке \"{0}\".\n\nДополнительную информацию см. в журнальном файле.",
```

And also two spelling fixes here:
```
"ui.main_window.menu_headers.view": "Просмотр",
"ui.message.unsaved_config_changes": "Обнаружены несохраненные изменения файлов конфигурации для профиля {0}.\n\nСохранить изменения?",
```
Everything else seems to be hunky-dory.

**Comment by Floogen** [comment]
I've adjusted the spelling according to your feedback!

I just noticed the line `"ui.settings_window.labels.mod_path": "Mod Folder Path"` is not translated. Would "Путь к папке мода" be a valid value (via Google Translate) or do you have a more proper string?

**Comment by Rongarah** [comment]
Sorry, missed that one. Here's proper translation:
`"ui.settings_window.labels.mod_path": "Путь к папке с модификацией"`

**Comment by Floogen** [comment]
Wonderful, thank you for your patience and help with translating! I'll be including your translation in the next release, which should come later today / tomorrow.

Thank you again for your efforts in translating Stardrop!

**Comment by Rongarah** [comment]
One more thing, missed "Note" words in three lines thinking it was part of the code, here are the correct ones:
```
  "ui.message.confirm_bulk_change_mod_states_enable": "Включить все модификации?\n\nПримечание: Это действие не может быть отменено.",
  "ui.message.confirm_bulk_change_mod_states_disable": "Отключить все модификации?\n\nПримечание: Это действие не может быть отменено.",
  "ui.message.confirm_mod_update_method": "Обнаружена более старая версия модификации {0}. Удалить старую версию?\n\nПримечание: Как правило рекомендуется удалить старую версию модификации, однако все файлы конфигурации будут потеряны.",
```

Basically, replace "Note" with "Примечание" :)

**Comment by Floogen** [comment]
Fixed, thank you!

**Pull request merged**
